import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/context/CartContext";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={inter.className}>
            <CartContextProvider>
                <body >{children}</body>
            </CartContextProvider>
        </html>
    );
}
